const ROLES = Object.freeze({
    STUDENT: 'STUDENT',
    STAFF: 'STAFF',
    MENTOR: 'MENTOR',
    SUPERADMIN: 'SUPERADMIN',
});

const SUBJECT_TYPES = Object.freeze({
    FULL_THEORY: 'FULL_THEORY',
    FULL_LAB: 'FULL_LAB',
    THEORY_WITH_LAB: 'THEORY_WITH_LAB',
});

const ANNOUNCEMENT_TYPES = Object.freeze({
    SYSTEM: 'SYSTEM',
    INFO: 'INFO',
    WARNING: 'WARNING',
    ALERT: 'ALERT',
});

const RATE_LIMITS = Object.freeze({
    LOGIN: { max: 5, timeWindow: '1 minute' },
    REGISTER_MENTOR: { max: 3, timeWindow: '10 minutes' },
    CHANGE_PASSWORD: { max: 3, timeWindow: '5 minutes' },
    PREDICT: { max: 5, timeWindow: '1 minute' },
    QA: { max: 3, timeWindow: '1 minute' },
    CHAT: { max: 10, timeWindow: '1 minute' },
    IMPERSONATE: { max: 5, timeWindow: '1 minute' },
    BROADCAST: { max: 3, timeWindow: '5 minutes' },
    COLLEGE_WRITE: { max: 10, timeWindow: '1 minute' },
    COLLEGE_DELETE: { max: 5, timeWindow: '1 minute' },
    GLOBAL: { max: 100, timeWindow: '1 minute' },
});

const PAGINATION = Object.freeze({
    DEFAULT_PAGE: 1,
    DEFAULT_LIMIT: 50,
    MAX_LIMIT: 100,
    DEFAULT_AUDIT_TAKE: 100,
    DEFAULT_SEARCH_TAKE: 20,
    MAX_USER_FETCH: 200,
});

const FILE_LIMITS = Object.freeze({
    MAX_BODY_BYTES: 10485760,       // 10MB
    UPLOAD_FILE_BYTES: 5242880,     // 5MB
    ASSIGNMENT_BYTES: 10485760,     // 10MB
    MATERIAL_BYTES: 20971520,       // 20MB
    SIGNATURE_BYTES: 2097152,       // 2MB
    EXCEL_BYTES: 5242880,           // 5MB
    MAX_FILES: 1,
});

const AUTH = Object.freeze({
    JWT_EXPIRY: '7d',
    JWT_MIN_SECRET_LENGTH: 32,
    BCRYPT_DEFAULT_ROUNDS: 12,
    IMPERSONATE_EXPIRY: '15m',
    COOKIE_NAME: 'token',
    COOKIE_MAX_AGE: 7 * 24 * 60 * 60,
    PASSWORD_MIN_LENGTH: 8,
    PASSWORD_MAX_LENGTH: 128,
});

const HTTP_STATUS = Object.freeze({
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    TOO_MANY_REQUESTS: 429,
    INTERNAL_SERVER_ERROR: 500,
    SERVICE_UNAVAILABLE: 503,
});

const ERROR_CODES = Object.freeze({
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
    AUTH_INSUFFICIENT_ROLE: 'AUTH_INSUFFICIENT_ROLE',
    AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
    AUTH_INVALID_PASSWORD: 'AUTH_INVALID_PASSWORD',
    AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
    PASSWORD_CHANGE_ERROR: 'PASSWORD_CHANGE_ERROR',
    BOOTSTRAP_DISABLED: 'BOOTSTRAP_DISABLED',
    BOOTSTRAP_SECRET_INVALID: 'BOOTSTRAP_SECRET_INVALID',
    BOOTSTRAP_ERROR: 'BOOTSTRAP_ERROR',
    REGISTRATION_ERROR: 'REGISTRATION_ERROR',
    EMAIL_EXISTS: 'EMAIL_EXISTS',
    DB_UNIQUE_CONSTRAINT: 'DB_UNIQUE_CONSTRAINT',
    DB_FOREIGN_KEY: 'DB_FOREIGN_KEY',
    DB_NOT_FOUND: 'DB_NOT_FOUND',
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
    CORS_DENIED: 'CORS_DENIED',
    FILE_TOO_LARGE: 'FILE_TOO_LARGE',
    FILE_TYPE_REJECTED: 'FILE_TYPE_REJECTED',

    UPLOAD_ERROR: 'UPLOAD_ERROR',
    MAINTENANCE_MODE: 'MAINTENANCE_MODE',
    NETWORK_ERROR: 'NETWORK_ERROR',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
    AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
    AUTH_DISABLED: 'AUTH_DISABLED',
});

module.exports = {
    ROLES,
    SUBJECT_TYPES,
    ANNOUNCEMENT_TYPES,
    RATE_LIMITS,
    PAGINATION,
    FILE_LIMITS,
    AUTH,
    HTTP_STATUS,
    ERROR_CODES,
};
